# Pandas

pandas is an open source, BSD licensed library providing high performance, easy to use data structure and data analysis tools for the python progg language

 Berkeley Source Distribution (BSD)
 
 1. What is Data Frame?
 2. What is Data Series?
 3. Different operation in Pandas

In [1]:
#import the pandas library
import numpy as np
import pandas as pd

In [2]:
df = pd.DataFrame(np.arange(0,20).reshape(5,4), index=['Ro1','Ro2','Ro3','Ro4','Ro5'],columns=['Col1','Col2','Col3','Col4'])

In [3]:
df

Col1  Col2  Col3  Col4
Ro1     0     1     2     3
Ro2     4     5     6     7
Ro3     8     9    10    11
Ro4    12    13    14    15
Ro5    16    17    18    19

In [5]:
df.head()

Col1  Col2  Col3  Col4
Ro1     0     1     2     3
Ro2     4     5     6     7
Ro3     8     9    10    11
Ro4    12    13    14    15
Ro5    16    17    18    19

In [6]:
#converting df to CSV file
df.to_csv('example.csv')

In [8]:
#accessing the elements
df.loc['Ro1']

Col1    0
Col2    1
Col3    2
Col4    3
Name: Ro1, dtype: int32

In [9]:
type(df.loc['Ro2'])

pandas.core.series.Series

In [10]:
df.iloc[:,:]

Col1  Col2  Col3  Col4
Ro1     0     1     2     3
Ro2     4     5     6     7
Ro3     8     9    10    11
Ro4    12    13    14    15
Ro5    16    17    18    19

In [13]:
df.iloc[1:4,1:4]

Col2  Col3  Col4
Ro2     5     6     7
Ro3     9    10    11
Ro4    13    14    15

In [14]:
type(df.iloc[0:1,0:1])

pandas.core.frame.DataFrame

In [15]:
type(df.iloc[0:1,0:5])

pandas.core.frame.DataFrame

In [19]:
df.loc['Ro1']

Col1    0
Col2    1
Col3    2
Col4    3
Name: Ro1, dtype: int32

In [20]:
type(df.loc['Ro1'])

pandas.core.series.Series

In [23]:
df.iloc[0:1,2]

Ro1    2
Name: Col3, dtype: int32

In [27]:
df.iloc[0:3,0]

Ro1    0
Ro2    4
Ro3    8
Name: Col1, dtype: int32

In [29]:
type(df.iloc[0:3,0:3])

pandas.core.frame.DataFrame

In [30]:
df.iloc[0:3,0:3]

Col1  Col2  Col3
Ro1     0     1     2
Ro2     4     5     6
Ro3     8     9    10

In [31]:
df.iloc[0:3,0]

Ro1    0
Ro2    4
Ro3    8
Name: Col1, dtype: int32

In [32]:
type(df.iloc[0:3,0])

pandas.core.series.Series

In [33]:
df.iloc[:,:].values

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [35]:
df.iloc[:,1:].values

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15],
       [17, 18, 19]])

In [36]:
df.iloc[:,1:].values

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15],
       [17, 18, 19]])

In [37]:
df.isnull().sum()

Col1    0
Col2    0
Col3    0
Col4    0
dtype: int64

In [38]:
df

Col1  Col2  Col3  Col4
Ro1     0     1     2     3
Ro2     4     5     6     7
Ro3     8     9    10    11
Ro4    12    13    14    15
Ro5    16    17    18    19

In [42]:
df.isnull().sum()

Col1    0
Col2    0
Col3    0
Col4    0
dtype: int64

In [46]:
df['Col1'].value_counts()

12    1
4     1
16    1
8     1
0     1
Name: Col1, dtype: int64

In [49]:
df['Col1'].unique()

array([ 0,  4,  8, 12, 16])

In [53]:
df[['Col2','Col3']].value_counts()

Col2  Col3
17    18      1
13    14      1
9     10      1
5     6       1
1     2       1
dtype: int64

In [52]:
type(df[['Col2','Col3']])

pandas.core.frame.DataFrame